spring:
  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 0

collector:
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    topic: stats.user-actions.v1
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
    acks: 1
    linger-ms: 5
    batch-size: 16384
    buffer-memory: 33554432

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always